services:
  # Backend API Server (Free Tier)
  - type: web
    name: iedcapi
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    healthCheckPath: /api/health
    # Environment variables to be set in Render dashboard:
    # NODE_ENV=production
    # MONGODB_URI=your_mongodb_connection_string
    # JWT_SECRET=your_secure_jwt_secret
    # EMAIL_USER=your_email@gmail.com
    # EMAIL_PASS=your_app_password
    # EMAIL_SERVICE=gmail
    # EMAIL_FROM="IEDC LBSCEK" <noreply@example.com>

  # Frontend Static Site (Free Tier)
  - type: web
    name: iedcweb
    env: static
    plan: free
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    # Environment variables to be set in Render dashboard:
    # VITE_API_URL=https://iedcapi.onrender.com
